// <auto-generated />
using System;
using AdopetAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdopetAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AdopetAPI.Models.Pet", b =>
                {
                    b.Property<int>("Pet_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DtInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Pet_Caracteristicas")
                        .HasColumnType("longtext");

                    b.Property<string>("Pet_Cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Pet_Especie")
                        .HasColumnType("int");

                    b.Property<int>("Pet_Idade")
                        .HasColumnType("int");

                    b.Property<string>("Pet_Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Pet_ResponsavelResp_Id")
                        .HasColumnType("int");

                    b.Property<string>("Pet_UF")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Pet_Id");

                    b.HasIndex("Pet_ResponsavelResp_Id");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("AdopetAPI.Models.Responsavel", b =>
                {
                    b.Property<int>("Resp_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DtInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DtUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Resp_Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Resp_Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Resp_Id");

                    b.ToTable("Responsaveis");
                });

            modelBuilder.Entity("AdopetAPI.Models.Tutor", b =>
                {
                    b.Property<int>("Tutor_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DtInsert")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DtUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Pet_Cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pet_UF")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tutor_Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tutor_Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tutor_Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Tutor_Id");

                    b.ToTable("Tutores");
                });

            modelBuilder.Entity("AdopetAPI.Models.Pet", b =>
                {
                    b.HasOne("AdopetAPI.Models.Responsavel", "Pet_Responsavel")
                        .WithMany()
                        .HasForeignKey("Pet_ResponsavelResp_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet_Responsavel");
                });
#pragma warning restore 612, 618
        }
    }
}
